version: "3.9"

services:
  app:
    build: .
    container_name: magpie_app
    ports:
      - "8082:8082"
    env_file:
      - backend/.env        # keeps secrets out of compose
    environment:
      - redisUrl=redis://host.docker.internal:8946
      - DB_HOST=host.docker.internal
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: magpie_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: magpie
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: magpie_redis
    ports:
      - "8946:6379"
    restart: unless-stopped

volumes:
  postgres_data:
