version: "3.9"

services:
  backend:
    build: .
    container_name: magpie_backend
    ports:
      - "5656:5656"
      - "20000-20100:20000-20100"
    env_file:
      - backend/.env        # keeps secrets out of compose
    environment:
      - redisUrl=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - GITHUB_UPDATES_LOCAL_SHA=${MAGPIE_GIT_COMMIT:-}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        BUILD_COMMIT: ${MAGPIE_GIT_COMMIT:-dev}
    container_name: magpie_frontend
    ports:
      - "5050:80"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: magpie_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: magpie
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: magpie_redis
    ports:
      - "8946:6379"
    restart: unless-stopped

volumes:
  postgres_data:
