services:
  postgres:
    image: postgres:17
    container_name: magpie_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: magpie
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: magpie_redis
    ports:
      - "8946:6379"
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
